In [30]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [31]:
credit_data = pd.read_csv('/content/creditcard.csv')

In [32]:
credit_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [33]:
#v are the deatures about each transaction
# time isthe time elapsed since the first transaction
# amount in usd
# class is used to check whether the trans is legit or not (1 is fradulant)
credit_data.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [34]:
credit_data.shape

(284807, 31)

In [35]:
credit_data.info()
#no missing values (ie null)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [36]:
# check missing values
credit_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [37]:
#check dist of legit transac and frauds
credit_data['Class'].value_counts()
#this dataset is very unbalanced
#initial data cannot be used to predict fraud cause the fraud data points are very less
# thus pre processing is needed

0    284315
1       492
Name: Class, dtype: int64

In [38]:
# 0 -> normal transaction
# 1 -> fraud transaction
# we seperate the data for analysis
legit = credit_data[credit_data.Class == 0]
fraud = credit_data[credit_data.Class == 1]

In [39]:
credit_data.shape

(284807, 31)

In [40]:
legit.shape

(284315, 31)

In [41]:
fraud.shape

(492, 31)

In [42]:
# stat measure
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [43]:
fraud.Amount.describe()
# we can observe that mean value is much greater

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [44]:
# compare values
credit_data.groupby('Class').mean()
#check the times

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [45]:
# small dist ds for legit and fraud
# check dist is even (random sample)
legit_sample = legit.sample(n=492)

In [46]:
df = pd.concat([legit_sample,fraud],axis = 0)
#adding row wise

In [47]:
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
271364,164539.0,-2.136451,1.284107,-0.776880,-1.850742,1.702532,4.086163,-0.882889,1.446847,0.749927,...,0.376285,0.748184,-0.122779,0.752149,-0.479615,0.357688,-1.980084,-0.674807,4.01,0
284407,172414.0,-3.631750,3.163347,0.193532,-1.998358,0.267031,-0.061255,0.963103,-0.621997,3.637450,...,-0.622863,-0.715340,-0.016132,0.483005,0.092736,-0.458080,-0.008775,0.038557,1.54,0
237920,149454.0,1.926699,-0.086505,-1.393894,0.421776,0.134298,-0.459857,-0.165623,-0.027920,0.430727,...,-0.048744,-0.098406,0.210460,0.693133,-0.265099,0.340916,-0.049330,-0.023751,38.22,0
159799,112973.0,-0.232813,0.734494,-1.392240,-1.120586,3.708127,3.379533,1.077868,0.478400,-0.345353,...,0.036745,0.185837,-0.399887,0.694492,0.730932,-0.613068,-0.447813,-0.303193,13.99,0
183015,125619.0,0.098882,0.901485,-0.169958,-0.893272,1.152915,-0.155926,1.003506,-0.096601,-0.164381,...,-0.297541,-0.659562,0.010137,-0.007671,-0.348587,0.152701,0.250565,0.098514,5.16,0

In [49]:
df.shape

(984, 31)

In [50]:
df.tail()
#fraud

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [51]:
df['Class'].value_counts()
# now we have a uniform data

0    492
1    492
Name: Class, dtype: int64

In [52]:
df.groupby('Class').mean()
#mean is constatnt as the og so data set is still consistent i.e good sample

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94886.347561,0.048566,-0.076909,0.065514,-0.100181,0.005126,-0.013155,0.018814,0.053305,-0.041509,...,-0.033214,-0.016843,0.013397,0.004333,0.04036,-0.028423,-0.009737,-0.003842,-0.003294,84.421667
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.10513,0.041449,0.051648,0.170575,0.075667,122.211321

In [53]:
#spilt daata
X = df.drop(columns = 'Class',axis = 1) #column
Y = df['Class']

In [54]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
271364  164539.0 -2.136451  1.284107 -0.776880 -1.850742  1.702532  4.086163
284407  172414.0 -3.631750  3.163347  0.193532 -1.998358  0.267031 -0.061255
237920  149454.0  1.926699 -0.086505 -1.393894  0.421776  0.134298 -0.459857
159799  112973.0 -0.232813  0.734494 -1.392240 -1.120586  3.708127  3.379533
183015  125619.0  0.098882  0.901485 -0.169958 -0.893272  1.152915 -0.155926
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
271364 -0.882889  1.446847  0.749927  ... -0.274817  0.376285  0.748184
284407  0.963103 -0.621997  3.637450  ...  1.823955 -0.622863 -0.715340
237920 -0.165623 -0.027920  0.430727  ... -0.045825 -0.048744 -0.098406
159799  1.077868  0.478400 -0.345353  ... -0.231277  0.036745  0.185837
183015  1.003506 -0.096601 -0.164381  ...  0.080082 -0.297541 -0.659562
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
271364 -0.122779  0.752149 -0.479615  0.357688 -1.980084 -0.674807    4.01
284407 -0.016132  0.483005  0.092736 -0.458080 -0.008775  0.038557    1.54
237920  0.210460  0.693133 -0.265099  0.340916 -0.049330 -0.023751   38.22
159799 -0.399887  0.694492  0.730932 -0.613068 -0.447813 -0.303193   13.99
183015  0.010137 -0.007671 -0.348587  0.152701  0.250565  0.098514    5.16
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [55]:
print(Y) #labels

271364    0
284407    0
237920    0
159799    0
183015    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [56]:
# train and test data
# 20% of data
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, stratify = Y, random_state = 2)

In [57]:
print(X.shape, X_train.shape,X_test.shape)

(984, 30) (787, 30) (197, 30)

In [58]:
#model training
# log reg (binary data 1/0)
model = LogisticRegression()

In [59]:
# training with data
model.fit(X_train,Y_train)

LogisticRegression()

In [60]:
#evaluation
# using training data
X_train_prediction = model.predict(X_train)
# compare values
train_accuracy = accuracy_score(X_train_prediction,Y_train)

In [61]:
print('Train Accuracy :',train_accuracy)
# check score for train data

Train Accuracy : 0.9263024142312579

In [64]:
X_test_prediction = model.predict(X_test)
test_accuracy = accuracy_score(X_test_prediction,Y_test)
# for test data
# accuracy score should somewhat match or else model is over/underfitted

In [65]:
print('Test accuracy score: ',test_accuracy)

Test accuracy score:  0.9187817258883249